# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\"M\n\x0e\x41\x64\x64TaskRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08\x64ue_date\x18\x04 \x01(\t\"\x1d\n\x0f\x41\x64\x64TaskResponse\x12\n\n\x02id\x18\x01 \x01(\t25\n\x05Tasks\x12,\n\x07\x41\x64\x64Task\x12\x0f.AddTaskRequest\x1a\x10.AddTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDTASKREQUEST']._serialized_start=14
  _globals['_ADDTASKREQUEST']._serialized_end=91
  _globals['_ADDTASKRESPONSE']._serialized_start=93
  _globals['_ADDTASKRESPONSE']._serialized_end=122
  _globals['_TASKS']._serialized_start=124
  _globals['_TASKS']._serialized_end=177
# @@protoc_insertion_point(module_scope)
